---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# logisticReg

<!-- badges: start -->
<!-- badges: end -->

The `logisticReg` package provides a custom implementation of logistic regression using Iteratively Reweighted Least Squares (IRLS).

## Installation

You can install the development version from GitHub:

```{r install-logisticReg, eval = FALSE}
devtools::install_github("jrjnn/logisticReg")
```

## Example

Here’s an example of using logistic_reg to fit a logistic regression model:

```{r logistic-example}
library(logisticReg)

set.seed(123)
X <- cbind(1, matrix(rnorm(100), ncol = 2))
y <- rbinom(50, 1, prob = 0.5)

result <- logistic_reg(X, y)
print(result)

```

Comparison with glm:
```{r glm-comparison}
glm_result <- coef(glm(y ~ X[, -1], family = binomial))
print(glm_result)
```
