name: Code Coverage Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  coverage:
    name: Generate Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev pandoc

      - name: Install R dependencies
        run: |
          R -e "install.packages('remotes')"
          R -e "remotes::install_deps(dependencies = TRUE)"
          R -e "install.packages('covr')"

      - name: Run unit tests and generate coverage report
        run: |
          R -e "covr::package_coverage(type = 'all')"
          R -e "covr::codecov()"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
