name: LogisticReg R Package CI Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Set up R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'
      
      - name: Install R dependencies
        run: |
          install.packages('remotes')
          remotes::install_deps(dependencies = TRUE)
          
      - name: Run R CMD check
        run: |
          R CMD build .
          R CMD check *tar.gz --no-manual --as-cran
          
      - name: Upload R CMD check results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: R-CMD-check-results
          path: '*Rcheck/'
